version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    container_name: "rabbitmq"
    ports:
      - "5672:5672"  # AMQP protocol port
      - "15672:15672" # Management UI port
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3

  web:
    build: .
    container_name: "seo_audit_web"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      rabbitmq:
        condition: service_healthy

  worker:
    build: .
    container_name: "seo_audit_worker"
    volumes:
      - .:/app
    env_file:
      - .env
    command: >
      sh -c "celery -A workers.celery_app worker --loglevel=info"
    depends_on:
      rabbitmq:
        condition: service_healthy 