import {expect,test} from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

test('real API: owner onboarding, connections, content, reports and mobile navigation',async({page})=>{
  const crashes:string[]=[]
  page.on('pageerror',error=>crashes.push(error.message))
  await page.goto('/')
  await page.getByLabel('Your name').fill('Pilot Owner')
  await page.getByLabel('Work email').fill('pilot@example.test')
  await page.getByLabel('Workspace name').fill('Independent Pilot')
  await page.getByLabel('Password',{exact:false}).fill('A-long-local-test-passphrase!57')
  await page.getByLabel('Deployment setup token').fill('test-only-bootstrap-token')
  await page.getByRole('button',{name:'Create workspace'}).click()
  await expect(page).toHaveURL(/sites\/new$/)
  await page.getByLabel('Site name').fill('Independent Workshop')
  await page.getByLabel('Site origin').fill('https://independent.example')
  await page.getByLabel('Business name').fill('Independent Workshop')
  await page.getByLabel('Primary audience').fill('Local customers')
  await page.getByRole('textbox',{name:'Services',exact:true}).fill('Repairs')
  await page.getByRole('textbox',{name:'Services',exact:true}).press('Enter')
  await page.getByRole('button',{name:'Create site'}).click()
  await expect(page).toHaveURL(/sites\/[a-f0-9]+\/overview$/)
  const siteId=page.url().split('/sites/')[1].split('/')[0]
  await expect(page.getByRole('heading',{name:'Independent Workshop',exact:true})).toBeVisible()
  const overview=await (await page.request.get(`/api/v1/sites/${siteId}/overview`)).json()
  expect(overview.coverage.status).toBe('not_checked')
  expect(overview.site.paused).toBe(true)
  const desktopAccessibility=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()
  expect(desktopAccessibility.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))})) ).toEqual([])
  await page.screenshot({path:'test-results/overview-desktop.png',fullPage:true})
  await page.goto(`/sites/${siteId}/settings/connections`)
  const wordpress=page.locator('form.connection-card').filter({hasText:'WordPress'}).first()
  await wordpress.getByLabel('Username',{exact:true}).fill('test-owner')
  await wordpress.getByLabel('Application password',{exact:true}).fill('test-only-not-live')
  await wordpress.getByRole('button',{name:'Save',exact:true}).click()
  await expect(page.getByText('WordPress settings saved.')).toBeVisible()
  const connections=await (await page.request.get(`/api/v1/sites/${siteId}/connections`)).json()
  expect(connections.items[0].status).toBe('needs_test')
  expect(JSON.stringify(connections)).not.toContain('test-only-not-live')
  await page.reload()
  await expect(wordpress.getByLabel('Application password',{exact:true})).toHaveValue('')
  await page.goto(`/sites/${siteId}/content/new`)
  await page.getByLabel('Title',{exact:false}).fill('A practical repair preparation guide')
  await page.getByLabel('Body',{exact:false}).fill('<p>Bring your repair questions to the workshop.</p>')
  await page.getByRole('button',{name:'Save article'}).click()
  await expect(page).toHaveURL(/content\/articles\/[a-f0-9]+$/)
  const checkedResponse=page.waitForResponse(response=>response.url().endsWith('/check') && response.request().method()==='POST')
  await page.getByRole('button',{name:'Check',exact:true}).click()
  expect((await checkedResponse).ok()).toBe(true)
  const articles=await (await page.request.get(`/api/v1/sites/${siteId}/articles`)).json()
  expect(articles.items[0].status).toBe('review_needed')
  expect(articles.items[0].checks.passed).toBe(false)
  for(const path of ['issues','pages','store','visibility','activity','incidents','publications','reports/weekly','settings/team','settings/policies']){
    await page.goto(`/sites/${siteId}/${path}`)
    await expect(page.locator('main h1')).toBeVisible()
  }
  await page.goto(`/sites/${siteId}/settings/policies`)
  await expect(page.getByRole('heading',{name:'Before enabling automation'})).toBeVisible()
  const readiness=page.getByRole('list',{name:'Automation readiness checklist'})
  await expect(readiness.getByRole('listitem').filter({hasText:'Always-on server'})).toContainText('Not Verified')
  await expect(readiness.getByRole('listitem').filter({hasText:'Encrypted backups and restore'})).toContainText('Not Verified')
  await expect(page.getByText('Do not enable automation yet',{exact:true})).toBeVisible()
  await page.setViewportSize({width:390,height:844})
  await page.getByRole('button',{name:'Open navigation'}).click()
  await expect(page.getByRole('navigation',{name:'Primary navigation'})).toBeVisible()
  await page.getByRole('link',{name:'Overview',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Independent Workshop',exact:true})).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  const mobileAccessibility=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()
  expect(mobileAccessibility.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))})) ).toEqual([])
  await page.screenshot({path:'test-results/overview-mobile.png',fullPage:true})
  expect(crashes).toEqual([])
})
