import { expect, test } from '@playwright/test'
import { verifyPlatformRendering } from './wordpress-render-check'

test('resume retained published operation: render, idempotent UI retry and rollback the same post', async ({ page, request }, testInfo) => {
  const metadata = await (await request.get('http://127.0.0.1:18082/__rehearsal')).json()
  const fixture = (await (await request.get('http://127.0.0.1:18082/__fixture')).json()).wordpress
  expect(metadata.resumed).toBe(true)
  expect(metadata.sites).toHaveLength(1)
  expect(metadata.articles_with_remote).toHaveLength(1)
  expect(metadata.sites[0].origin).toBe('https://wordpress.fixture.test')
  const siteId = metadata.sites[0].id
  const articleId = metadata.articles_with_remote[0].id
  const api = `/api/v1/sites/${siteId}`
  const get = async (path: string) => (await page.request.get(api + path)).json()
  await page.goto('/')
  await page.getByLabel('Email', { exact: false }).fill('rehearsal@example.test')
  await page.getByLabel('Password', { exact: false }).fill('Disposable-browser-password!57')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page).toHaveURL(/overview$/)

  // Old pre-retention harnesses lost their ephemeral encryption key. Reconnect
  // only this fixture using a newly issued fixture password, without touching
  // its persisted article, attempt, source snapshot or remote post.
  await page.goto(`/sites/${siteId}/settings/connections`)
  const wp = page.locator('form.connection-card').filter({ hasText: 'WordPress' }).first()
  page.once('dialog', dialog => dialog.accept())
  await wp.getByRole('button', { name: 'Revoke', exact: true }).click()
  await expect.poll(async () => (await get('/connections')).items.find((c: any) => c.kind === 'wordpress')?.status).toBe('revoked')
  await wp.getByLabel('Username', { exact: true }).fill(fixture.username)
  await wp.getByLabel('Application password', { exact: true }).fill(fixture.application_password)
  await wp.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByText('WordPress settings saved.')).toBeVisible()
  await wp.getByRole('button', { name: 'Test', exact: true }).click()
  await expect.poll(async () => (await get('/connections')).items.find((c: any) => c.kind === 'wordpress')?.status).toBe('connected')
  await page.goto(`/sites/${siteId}/content/articles/${articleId}`)
  await expect(page.getByRole('button', { name: 'Roll back publication' })).toBeVisible()
  const publication = (await get('/publications')).items.find((p: any) => p.article_id === articleId)
  const article = await get(`/articles/${articleId}`)
  expect(article.status).toBe('published')
  expect(publication.status).toBe('published')
  const renderJob = await verifyPlatformRendering(page, siteId, articleId, publication.result.url)
  const url = new URL(publication.result.url)
  expect(url.hostname).toBe('wordpress.fixture.test')
  const rendered = await page.context().newPage()
  await rendered.route('**/*', async route => {
    const target = new URL(route.request().url())
    if (target.hostname !== 'wordpress.fixture.test') return route.abort()
    const response = await route.fetch({ url: `http://127.0.0.1:18090${target.pathname}${target.search}`, headers: { ...route.request().headers(), Host: target.host, 'X-Forwarded-Proto': 'https' } })
    await route.fulfill({ response })
  })
  await rendered.goto(url.href, { waitUntil: 'domcontentloaded' })
  await expect(rendered.getByRole('heading', { name: 'Ask what the estimate includes', exact: true })).toBeVisible()
  await expect(rendered.getByRole('link', { name: /FTC.s Auto Repair Basics guide/ })).toHaveAttribute('href', 'https://consumer.ftc.gov/articles/0211-auto-repair-basics')
  await rendered.screenshot({ path: testInfo.outputPath('wordpress-rendered.png'), fullPage: true })
  await rendered.close()
  const firstJob = (await get('/jobs')).items.find((j: any) => j.kind === 'publish' && j.payload?.article_id === articleId)
  const retry = page.waitForResponse(r => r.url().endsWith(`/articles/${articleId}/publish`) && r.request().method() === 'POST')
  await page.getByRole('button', { name: 'Publish', exact: true }).click()
  expect((await (await retry).json()).id).toBe(firstJob.id)
  await expect(page.getByText('Publication completed and verification is recorded.')).toBeVisible()
  const headers = { Host: 'wordpress.fixture.test', 'X-Forwarded-Proto': 'https', Authorization: 'Basic ' + Buffer.from(`${fixture.username}:${fixture.application_password}`).toString('base64') }
  const matches = await request.get(`http://127.0.0.1:18090/wp-json/wp/v2/posts?context=edit&status=any&slug=${encodeURIComponent(article.slug)}`, { headers })
  const posts = await matches.json()
  expect(posts).toHaveLength(1)
  expect(String(posts[0].id)).toBe(publication.remote_id)
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'Roll back publication' }).click()
  await expect(page.getByText('Rollback completed and the remote record was verified.')).toBeVisible({ timeout: 45000 })
  const restored = await request.get(`http://127.0.0.1:18090/wp-json/wp/v2/posts/${publication.remote_id}?context=edit`, { headers })
  expect((await restored.json()).status).toBe('draft')
  expect((await get(`/articles/${articleId}`)).status).toBe('rolled_back')
  const history = (await get('/publications')).items.filter((p: any) => p.article_id === articleId)
  expect(history).toHaveLength(1)
  expect(history[0].id).toBe(publication.id)
  expect(history[0].status).toBe('rolled_back')
  await page.screenshot({ path: testInfo.outputPath('rolled-back.png'), fullPage: true })
  await testInfo.attach('resumed-rehearsal-evidence', { body: JSON.stringify({ evidence_directory: metadata.evidence_directory, site_id: siteId, article_id: articleId, publication_id: publication.id, remote_id: publication.remote_id, publish_job_id: firstJob.id, render_job_id: renderJob.id, browser_screenshot_sha256: renderJob.result.screenshot_sha256, remote_count_after_retry: posts.length, remote_final_status: 'draft', original_public_evidence: publication.result.evidence.sha256, fixture_reconnected: true }, null, 2), contentType: 'application/json' })
})
